### PR TITLE
Allow meta-attributes on enum variant fields

### PR DESCRIPTION
**Pull request by grego**
When a crate uses a public error type derived by `custom_error` and is compiled with `#![warn(missing_docs)]`, warnings are irremediably produced regarding missing documentation of enum variant fields.
This PR fixes it by allowing optional meta-attributes on these fields.
Also, running `cargo test` produced 14 warnings about unnecessary trailing semicolons, which is fixed here.

### CODE REVIEW

**Review by lovasoa — APPROVED** [review]

**Comment by lovasoa** [comment]
Thank you for your contribution !

**Comment by grego** [comment]
You are welcome :) Could you, please, publish a new version on crates?

**Comment by lovasoa** [comment]
I will :)

**Comment by lovasoa** [comment]
@grego done.

https://crates.io/crates/custom_error/versions

**Comment by grego** [comment]
Thank you!

**Pull request merged**
